// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Module2_Exam_Review.Models;

public partial class Book
{
    public int Id { get; set; }

    public string Author { get; set; }

    public string Title { get; set; }

    public double Price { get; set; }

    public string CoverImage { get; set; }

    public string Url { get; set; }
}