// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Module2_Exam_Review.Models;

public partial class DB_128040_pegasausContext : DbContext
{
    public DB_128040_pegasausContext()
    {
    }

    public DB_128040_pegasausContext(DbContextOptions<DB_128040_pegasausContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Book> Books { get; set; }

    public virtual DbSet<Purse> Purses { get; set; }

    public virtual DbSet<Wine> Wines { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=tcp:s19.winhost.com;Initial Catalog=DB_128040_pegasaus;Persist Security Info=True;User ID=student;Password=Buddy;TrustServerCertificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Book>(entity =>
        {
            entity.ToTable("Book");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Author)
                .IsRequired()
                .HasMaxLength(50)
                .IsFixedLength()
                .HasColumnName("author");
            entity.Property(e => e.CoverImage)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("cover_image");
            entity.Property(e => e.Price).HasColumnName("price");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(125)
                .IsFixedLength()
                .HasColumnName("title");
            entity.Property(e => e.Url)
                .IsRequired()
                .HasMaxLength(250)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Book_url")
                .HasColumnName("url");
        });

        modelBuilder.Entity<Purse>(entity =>
        {
            entity.ToTable("Purse");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Brand)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Color)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.InteriorPockets).HasColumnName("Interior_Pockets");
            entity.Property(e => e.Material)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Size)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.StrapLength).HasColumnName("Strap_Length");
        });

        modelBuilder.Entity<Wine>(entity =>
        {
            entity.ToTable("Wine");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Country)
                .HasMaxLength(255)
                .HasColumnName("country");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Designation)
                .HasMaxLength(255)
                .HasColumnName("designation");
            entity.Property(e => e.Points).HasColumnName("points");
            entity.Property(e => e.Price).HasColumnName("price");
            entity.Property(e => e.Province)
                .HasMaxLength(255)
                .HasColumnName("province");
            entity.Property(e => e.Region1)
                .HasMaxLength(255)
                .HasColumnName("region_1");
            entity.Property(e => e.Region2)
                .HasMaxLength(255)
                .HasColumnName("region_2");
            entity.Property(e => e.TasterName)
                .HasMaxLength(255)
                .HasColumnName("taster_name");
            entity.Property(e => e.TasterTwitterHandle)
                .HasMaxLength(255)
                .HasColumnName("taster_twitter_handle");
            entity.Property(e => e.Title)
                .HasMaxLength(255)
                .HasColumnName("title");
            entity.Property(e => e.Variety)
                .HasMaxLength(255)
                .HasColumnName("variety");
            entity.Property(e => e.Winery)
                .HasMaxLength(255)
                .HasColumnName("winery");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}