// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Module2_Exam_Review.Models;

public partial class Purse
{
    public short Id { get; set; }

    public string Brand { get; set; }

    public string Color { get; set; }

    public string Material { get; set; }

    public double Price { get; set; }

    public string Size { get; set; }

    public double StrapLength { get; set; }

    public byte InteriorPockets { get; set; }
}