// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Module2_Exam_Review.Models;

public partial class Wine
{
    public double Id { get; set; }

    public string Country { get; set; }

    public string Description { get; set; }

    public string Designation { get; set; }

    public double? Points { get; set; }

    public double? Price { get; set; }

    public string Province { get; set; }

    public string Region1 { get; set; }

    public string Region2 { get; set; }

    public string TasterName { get; set; }

    public string TasterTwitterHandle { get; set; }

    public string Title { get; set; }

    public string Variety { get; set; }

    public string Winery { get; set; }
}